version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - "18123:8123"    # HTTP 接口
      - "19000:9000"    # Native TCP 接口
      - "19009:9009"    # 用于内部通信（可选）
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: vfdeuiclgb
      CLICKHOUSE_DB: default
    volumes:
      - clickhouse_data:/var/lib/clickhouse       # 数据存储卷
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  clickhouse_data: